# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  # Define your ACR details
  acrName: 'strijboscr.azurecr.io'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to ACR
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo $(acrPassword) | docker login $(acrName) -u $(acrUsername) --password-stdin
      displayName: 'Login to ACR'
    
    - task: Docker@2
      displayName: Tag and Push
      inputs:
        command: push
        repository: '$(acrName)/whey-protein-comparer:$(tag)' # Replace with your image name and tag

# Reference the variable group
variables:
- group: whey-protein-comparer-variable-group