# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: whey-protein-comparer-variable-group
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build_and_deploy
  displayName: Build and Deploy to ACR
  jobs:
  - job: Build-and-Deploy
    displayName: Build and Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo $(acrPassword) | docker login $(acrName) -u $(acrUsername) --password-stdin
      displayName: 'Login to ACR'
    - script: |
        docker build -t $(acrName)/whey-protein-comparer:$(tag) . -f $(Build.SourcesDirectory)/Dockerfile
        docker push $(acrName)/whey-protein-comparer:$(tag)
      displayName: 'Tag and Push Docker image'

