# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: whey-protein-comparer-variable-group
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - script: |
        echo $(tag)

- stage: Deploy
  displayName: Deploy to ACR
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo $(acrPassword) | docker login $(acrName) -u $(acrUsername) --password-stdin
      displayName: 'Login to ACR'
    - script: |
        docker tag $(acrName)/whey-protein-comparer:$(tag) $(acrName)/whey-protein-comparer:$(tag)
        docker push $(acrName)/whey-protein-comparer:$(tag)
      displayName: 'Tag and Push Docker image'